project 'IFenQu.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IFenQu' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IFenQu

  target 'IFenQuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IFenQuUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'Masonry'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'IQKeyboardManager'
  pod 'MJRefresh'
  pod 'Bugly'
  pod 'WechatOpenSDK'
  pod 'HandyJSON', '4.0.0-beta.1'
  pod 'JPush'
  pod 'FMDB'
  pod 'MJExtension'
end
