project 'iFenQu.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iFenQu' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iFenQu


  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'Masonry'
  pod 'MJExtension'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'IQKeyboardManager'
  pod 'MJRefresh'
  pod 'Bugly'
end
